run:
  timeout: 5m
  go: '1.24'

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - ineffassign
    - staticcheck
    - unused
    - errcheck
    - gosimple
    - typecheck
    - misspell
    - unconvert
    - unparam
    - gocyclo
    - gocritic
    - revive
    - stylecheck

linters-settings:
  gocyclo:
    min-complexity: 15

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style

  revive:
    rules:
      - name: exported
        disabled: false
      - name: package-comments
        disabled: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
