// Code generated by protoc-gen-go. DO NOT EDIT.

package features

import "context"

// This file verifies that machine-generated sources are skipped entirely:
// the header above (before the package clause) marks the file as generated,
// so sigfmt must stay silent on everything in it — even signatures that
// would normally trigger diagnostics.

// GeneratedCollapsed would normally trigger a diagnostic (fits one line).
func GeneratedCollapsed(
	a int,
	b string,
) error {
	return nil
}

// GeneratedInterface packs params aggressively in hand-written code; here it
// must produce no diagnostics either.
type GeneratedInterface interface {
	Method(
		ctx context.Context,
		id string,
	) error
}
