// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package format

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/vsfedorenko/sigfmt/internal/domain"
	"github.com/vsfedorenko/sigfmt/internal/pkg/source"
)

// NewMockStrategy creates a new instance of MockStrategy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStrategy(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStrategy {
	mock := &MockStrategy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStrategy is an autogenerated mock type for the Strategy type
type MockStrategy struct {
	mock.Mock
}

type MockStrategy_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStrategy) EXPECT() *MockStrategy_Expecter {
	return &MockStrategy_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockStrategy
func (_mock *MockStrategy) Apply(file *source.File, sig *domain.Signature) (string, bool) {
	ret := _mock.Called(file, sig)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(*source.File, *domain.Signature) (string, bool)); ok {
		return returnFunc(file, sig)
	}
	if returnFunc, ok := ret.Get(0).(func(*source.File, *domain.Signature) string); ok {
		r0 = returnFunc(file, sig)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*source.File, *domain.Signature) bool); ok {
		r1 = returnFunc(file, sig)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockStrategy_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockStrategy_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - file *source.File
//   - sig *domain.Signature
func (_e *MockStrategy_Expecter) Apply(file any, sig any) *MockStrategy_Apply_Call {
	return &MockStrategy_Apply_Call{Call: _e.mock.On("Apply", file, sig)}
}

func (_c *MockStrategy_Apply_Call) Run(run func(file *source.File, sig *domain.Signature)) *MockStrategy_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *source.File
		if args[0] != nil {
			arg0 = args[0].(*source.File)
		}
		var arg1 *domain.Signature
		if args[1] != nil {
			arg1 = args[1].(*domain.Signature)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStrategy_Apply_Call) Return(s string, b bool) *MockStrategy_Apply_Call {
	_c.Call.Return(s, b)
	return _c
}

func (_c *MockStrategy_Apply_Call) RunAndReturn(run func(file *source.File, sig *domain.Signature) (string, bool)) *MockStrategy_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockStrategy
func (_mock *MockStrategy) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockStrategy_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockStrategy_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockStrategy_Expecter) Name() *MockStrategy_Name_Call {
	return &MockStrategy_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockStrategy_Name_Call) Run(run func()) *MockStrategy_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStrategy_Name_Call) Return(s string) *MockStrategy_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockStrategy_Name_Call) RunAndReturn(run func() string) *MockStrategy_Name_Call {
	_c.Call.Return(run)
	return _c
}
